version: "3.9" # optional since v1.27.0
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "4000:80"
        # use this if on same network
        # networks:
        #     - tpl_network
        environment:
            - IP=0.0.0.0
            - HOST=3000
# use this if on same network
# networks:
#     tpl_network: # {}
#         driver: bridge
