version: "3.9" # optional since v1.27.0
services:
    # redis:
    #     image: redis
    #     networks:
    #         - backend
    backend:
        build: server
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - ./server:/app
            - backend-node_modules:/app/node_modules
    frontend:
        build: client
        ports:
            - "3000:3000"
        networks:
            - backend
            - frontend
        volumes:
            - ./client:/app
            - frontend-node_modules:/app/node_modules

networks:
    frontend: {}
    backend: {}
volumes:
    backend-node_modules: {}
    frontend-node_modules: {}
