version: "3.9" # optional since v1.27.0
services:
    redis:
        image: redis
        container_name: cache
        networks:
            - backend
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - backend
        volumes:
            - ./server:/app
            - backend-node_modules:/app/node_modules
        environment:
            - IP=0.0.0.0
            - PORT=5000
            - REDIS_URL=redis://cache
            - NODE_ENV=development
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - backend
            - frontend
        volumes:
            - ./client:/app
            - frontend-node_modules:/app/node_modules
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - NODE_ENV=development

networks:
    frontend: {}
    backend: {}
volumes:
    backend-node_modules: {}
    frontend-node_modules: {}
