version: "3.9" # optional since v1.27.0
services:
    redis:
        image: redis
        container_name: cache
        networks:
            - backend
    backend:
        build: server
        expose:
            - "5000"
        networks:
            - backend
        environment:
            - IP=0.0.0.0
            - PORT=5000
            - REDIS_URL=redis://cache
            - NODE_ENV=production
    frontend:
        build:
            context: client
            dockerfile: Dockerfile.prod
        ports:
            - "1709:80"
        networks:
            - backend
            - frontend
        environment:
            # - HOST=0.0.0.0
            # - PORT=3000
            - NODE_ENV=production

networks:
    frontend: {}
    backend: {}
volumes:
    backend-node_modules: {}
    frontend-node_modules: {}
