version: "3.9" # optional since v1.27.0
services:
    redis:
        image: redis
        # container_name: cache
        networks:
            - backend
    backend:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "2195:5000"
        networks:
            - backend
        environment:
            - IP=0.0.0.0
            - PORT=5000
            - REDIS_URL=redis://redis

networks:
    backend: {}
